In [106]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense,Flatten

# Preparing the Dataset

In [66]:
data = pd.read_csv('Final_dataset.csv')

In [67]:
data.head()

,Unnamed: 0,Date flow,Dst IP Addr:Port,Durat,Flags,Flows,Label,Labels,Packets Bytes,Prot,Src IP Addr:Port,Tos,start time
0,0,2011-08-15,205.188.10.203:443,0.000,A_,60,1,LEGITIMATE,1,TCP,147.32.84.134:45266,0,11:00:05.704
1,1,2011-08-15,147.32.84.118:51463,4.996,PA_,84327,1,Background,58,TCP,62.44.1.18:80,0,11:00:05.704
2,2,2011-08-15,62.44.1.18:80,4.892,A_,1740,1,Background,29,TCP,147.32.84.118:51463,0,11:00:05.706
3,3,2011-08-15,147.32.85.103:18006,0.000,INT,175,1,Background,1,UDP,147.32.80.9:53,0,11:00:05.707
4,4,2011-08-15,147.32.80.9:53,0.000,INT,71,1,Background,1,UDP,147.32.85.103:41094,0,11:00:05.709

In [68]:
data.drop(['Unnamed: 0','Date flow','Dst IP Addr:Port','Label','Src IP Addr:Port','Tos','start time'],axis=1,inplace=True)

In [69]:
data.head()
data.columns

Index(['Durat', 'Flags', 'Flows', 'Labels', 'Packets Bytes', 'Prot'], dtype='object')

In [70]:
data.dropna(inplace = True)
data.drop_duplicates(inplace=True)

In [74]:
x = data[['Durat', 'Flows','Packets Bytes', 'Prot']]
y = data['Labels']
le = LabelEncoder()

In [75]:
y= le.fit_transform(y)
x['Prot']= le.fit_transform(x['Prot'])

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [76]:
x

         Durat   Flows  Packets Bytes  Prot
0        0.000      60              1    10
1        4.996   84327             58    10
2        4.892    1740             29    10
3        0.000     175              1    11
4        0.000      71              1    11
5        0.000     152              1    11
6        0.000      73              1    11
7        4.115     891             12    10
8        4.113     477              7    10
9        4.935   83105             61    10
10       4.935    1800             30    10
11       0.000      76              1    11
12       0.000     208              1    11
13       0.888    1946             30    10
14       4.989   82354             57    10
15       4.989    3300             55    10
16       0.000      80              1    11
17       0.000     130              1    11
18       0.000      93              1    11
19       0.000     143              1    11
21       0.000     202              1    11
22       0.000      90              1    11
23       0.000      60              1    10
24       0.000      85              1    11
25       0.000     228              1    11
26       0.000      83              1    11
27       0.000     205              1    11
28       0.018    4250              8    10
29       0.069     169              2    10
30       0.000     119              1    10
...        ...     ...            ...   ...
4237802  0.039     605              4    10
4237803  0.020     395              3    10
4237812  0.001     681              5    10
4237813  0.001     637              9    10
4237814  0.267     159              2    10
4237829  0.325    4567              5    10
4237832  0.640     660             10    10
4237863  0.630    7062            107    10
4237864  0.552     240              4    10
4237867  0.626  797878            527    10
4237873  0.434   67966             45    10
4237874  0.573    1836             30    10
4237877  0.366    9084              6    10
4237878  0.520    2806             44    10
4237889  0.424     834              7    10
4237905  0.374     516              6    10
4237957  0.316   10329              8    10
4237966  0.260    1051              6    10
4237967  0.325    1258              3    10
4237968  0.265    3922              6    10
4237969  0.235    3314             16    10
4237970  0.329     125              2    10
4237971  0.130    3143              4    10
4237978  0.223     872              6    10
4237997  0.124    3043              3    11
4237999  0.091     451              6    10
4238000  0.091     438              5    10
4238005  0.107    1784              5    10
4238007  0.071   36519             27    10
4238008  0.123     244              4    10

[909568 rows x 4 columns]

In [109]:
pohe = OneHotEncoder(categorical_features=[3])
p = ohe.fit_transform(x).toarray()

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 6.0000e+01,
        1.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 4.9960e+00, 8.4327e+04,
        5.8000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 4.8920e+00, 1.7400e+03,
        2.9000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0700e-01, 1.7840e+03,
        5.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 7.1000e-02, 3.6519e+04,
        2.7000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.2300e-01, 2.4400e+02,
        4.0000e+00]])

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(p,y,test_size =0.4)

# Building the Model

In [140]:
model = Sequential()
model.add(Dense(30,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [142]:
model.fit(x_train,y_train,epochs = 5)

Train on 545740 samples
Epoch 1/5
545740/545740 [==============================] - 18s 33us/sample - loss: 35.2452 - accuracy: 0.7635
Epoch 2/5
545740/545740 [==============================] - 18s 33us/sample - loss: 19.0907 - accuracy: 0.7870
Epoch 3/5
545740/545740 [==============================] - 18s 33us/sample - loss: 5.7223 - accuracy: 0.8259
Epoch 4/5
545740/545740 [==============================] - ETA: 0s - loss: 0.4269 - accuracy: 0.84 - 18s 33us/sample - loss: 0.4269 - accuracy: 0.8476
Epoch 5/5
545740/545740 [==============================] - 18s 33us/sample - loss: 0.4087 - accuracy: 0.8476

In [143]:
model.evaluate(x_test,y_test)

363828/363828 [==============================] - 8s 22us/sample - loss: 0.4084 - accuracy: 0.8462s - loss: 0.4084 - accura

[0.4084268809547695, 0.8461718]

In [155]:
# 84 % accuracy